#!/usr/bin/env python3
"""Generate a synthetic 23andMe-style export for demos and development.

    python scripts/make_demo_genome.py demo-genome.txt

Nobody should have to hand over their genome to work on this project, and the
alternative most projects reach for is committing "a real file, just one, from a
public dataset" — which is how openSNP participants ended up in repositories
they never agreed to. So: a generator instead of a fixture.

The output is realistic where realism matters and fake everywhere else. It has
the size, the header, the no-call rate, and the chromosome distribution of a real
export, so the parser and its diagnostics get exercised properly. The genotypes
at catalog markers are chosen by hand to make the demo interesting, and the other
~600,000 are random noise at invented positions. It is not anyone's DNA, and it
never was.

Deterministic by default, so a demo run looks the same twice and a bug report
can name a seed.
"""

from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path

#: Chosen to exercise the catalog rather than to describe a person. The APOE
#: pair gives e3/e4, which is the most interesting result the tool can produce
#: and the one whose handling is worth showing.
DEMO_CALLS: dict[str, tuple[str, str, str]] = {
    # rsid: (chromosome, position, genotype)
    "rs762551": ("15", "75041917", "AC"),  # CYP1A2, intermediate caffeine
    "rs9939609": ("16", "53820527", "AT"),  # FTO, one copy
    "rs7903146": ("10", "114758349", "CT"),  # TCF7L2, one risk copy
    "rs1801133": ("1", "11856378", "CT"),  # MTHFR, the overhyped one
    "rs429358": ("19", "45411941", "CT"),  # APOE, with rs7412 below -> e3/e4
    "rs7412": ("19", "45412079", "CC"),
    "rs2802292": ("6", "108987709", "GT"),  # FOXO3, one longevity copy
    "rs4149056": ("12", "21331549", "TT"),  # SLCO1B1, typical statin transport
    "rs671": ("12", "112241766", "GG"),  # ALDH2, typical
    "rs10455872": ("6", "161010118", "AA"),  # LPA, no risk copies
    # HFE compound heterozygote: one C282Y, one H63D. Chosen because it is the
    # category that only exists when both SNPs are read together.
    "rs1800562": ("6", "26093141", "AG"),  # HFE C282Y, one copy
    "rs1799945": ("6", "26091179", "CG"),  # HFE H63D, one copy
    # Factor V Leiden carrier, written plus-strand (the literature says G>A).
    "rs6025": ("1", "169519049", "CT"),
    "rs1799963": ("11", "46761055", "GG"),  # F2, no variant
}

HEADER = """\
# This data file generated by 23andMe at: Wed Jul 15 09:00:00 2026
#
# THIS IS A SYNTHETIC FILE. It was produced by scripts/make_demo_genome.py in the
# dnadistiller repository. It is not derived from any person's DNA. The genotypes at
# known markers were chosen by hand to demonstrate the tool; every other row is
# random noise at invented positions.
#
# Below is a text version of your data.  Fields are TAB-separated
# Each line corresponds to a single SNP.  For each SNP, we provide its identifier
# (an rsid or an internal id), its location on the reference human genome, and the
# genotype call oriented with respect to the plus strand on the human reference
# sequence.  We are using reference human assembly build 37 (also known as
# Annotation Release 104).
#
# rsid	chromosome	position	genotype
"""

#: Roughly proportional to real chip content, which is itself roughly
#: proportional to chromosome length. Only needs to be close enough that the
#: per-chromosome table in `dnadistiller check` looks plausible.
CHROMOSOME_WEIGHTS: dict[str, float] = {
    **{str(n): w for n, w in enumerate(
        [8.0, 8.2, 6.7, 6.2, 6.0, 5.8, 5.2, 4.8, 4.1, 4.6, 4.5,
         4.4, 3.3, 3.0, 2.8, 2.9, 2.6, 2.6, 2.0, 2.1, 1.3, 1.4],
        start=1,
    )},
    "X": 3.5,
    "Y": 0.3,
    "MT": 0.05,
}


def build(out: Path, *, variants: int, seed: int, no_call_rate: float) -> None:
    rng = random.Random(seed)
    bases = "ACGT"

    chromosomes = list(CHROMOSOME_WEIGHTS)
    weights = list(CHROMOSOME_WEIGHTS.values())

    with out.open("w", encoding="utf-8") as handle:
        handle.write(HEADER)

        # Catalog markers first, so a reader opening the file sees the
        # interesting rows rather than 600,000 lines of noise.
        for rsid, (chromosome, position, genotype) in DEMO_CALLS.items():
            handle.write(f"{rsid}\t{chromosome}\t{position}\t{genotype}\n")

        # Filler. rsIDs start high enough not to collide with the real ones above.
        for i in range(variants):
            rsid = f"rs{9_000_000 + i}"
            chromosome = rng.choices(chromosomes, weights=weights, k=1)[0]
            position = rng.randint(1, 250_000_000)

            if rng.random() < no_call_rate:
                genotype = "--"
            elif chromosome in ("Y", "MT"):
                # Haploid: one copy, so one letter. The parser has a path for
                # this and it should be exercised.
                genotype = rng.choice(bases)
            else:
                genotype = "".join(sorted(rng.choices(bases, k=2)))

            handle.write(f"{rsid}\t{chromosome}\t{position}\t{genotype}\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path, nargs="?", default=Path("demo-genome.txt"))
    parser.add_argument(
        "--variants",
        type=int,
        default=630_000,
        help="Filler variants. Default matches a real 23andMe v5 export.",
    )
    parser.add_argument("--seed", type=int, default=42, help="For reproducible demos.")
    parser.add_argument(
        "--no-call-rate",
        type=float,
        default=0.012,
        help="Fraction of failed calls. Real exports run about 1-2%%.",
    )
    args = parser.parse_args()

    build(args.output, variants=args.variants, seed=args.seed, no_call_rate=args.no_call_rate)

    size_mb = args.output.stat().st_size / 1_000_000
    print(f"Wrote {args.output} ({size_mb:.1f} MB, {args.variants + len(DEMO_CALLS):,} variants)")
    print("Synthetic. Not anyone's DNA. Safe to share, safe to delete.")
    print(f"\n  dnadistiller check {args.output}")
    print(f"  dnadistiller profile {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
